name: 'dbt_bigquery_ecommerce'
version: '1.5.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"          # directory which will store compiled SQL files
clean-targets:                 # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
  dbt_bigquery_ecommerce:
    ecommerce: 
      +materialized: view      # models will be stored as views by default
